name: Publish ApplicationRecord to Registry
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - '*'

env:
  CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
  CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}

jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # though you need version 14 with geojson
      - name: "Install Yarn"
        run: |
          npm install -g yarn
          npm install -g typescript

      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
          laconic --version
      - name: "Install jq"
        uses: dcarbone/install-jq-action@v2.1.0
      - name: "Publish App Record"
        run: scripts/publish-app-record.sh
